### PR TITLE
Improve error logs when http request fail

### PR DESCRIPTION
**Pull request by mtuchi**
### Description 
Improve error logging for `EAI_AGAIN`, `ENOTFOUND` and  `UNABLE_TO_VERIFY_LEAF_SIGNATURE`

### Related issue
This fixes https://github.com/OpenFn/primero-thailand/issues/72#issuecomment-1285169983

### Important Notes ⚠️ 
This update requires `language-http@v4.0.0`, It was tested in the environment 👇🏽 
```
╭─────────────────────────────────────────────╮
│ ◲ ◱  @openfn/core#v1.4.8 (Node.js v18.10.0) │
│ ◳ ◰             @openfn/language-http@4.0.0 │
╰─────────────────────────────────────────────╯
```

### CODE REVIEW

**Comment by mtuchi** [comment]
When an error has a code `ENOTFOUND`
The expected output 
```
The Url 'PRIMERO API URL for User Authentication' Is invalid
Please check the url in configuration and update accordingly
{
  hostname: 'PRIMERO API URL',
  url: 'PRIMERO API URL for User Authentication',
  method: 'post',
  data: { email: 'useremail', password: '******' },
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    cookie: '',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 54
  }
}
```

**Comment by mtuchi** [comment]
When an error has a code `EAI_AGAIN`
The expected output 
```
DNS lookup for 'PRIMERO API URL for User Authentication' has timed out
Either network connectivity error, proxy error or Invalid DNS nameserver response
{
  hostname: 'PRIMERO API URL',
  url: 'PRIMERO API URL for User Authentication',
  method: 'post',
  data: { email: 'useremail', password: '******' },
  headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    cookie: '',
    'User-Agent': 'axios/0.21.4',
    'Content-Length': 54
  }
}
```

**Comment by aleksa-krolls** [comment]
@mtuchi before I merge, can you please explain why ` strictSSL: false` was removed? Did we originally add this to try to get around the `EAI` error?

**Comment by mtuchi** [comment]
> @mtuchi before I merge, can you please explain why ` strictSSL: false` was removed? Did we originally add this to try to get around the `EAI` error?

@aleksa-krolls the job has been updated to use the latest `language-http@4.0.0` adaptor 
```
╭─────────────────────────────────────────────╮
│ ◲ ◱  @openfn/core#v1.4.8 (Node.js v18.10.0) │
│ ◳ ◰             @openfn/language-http@4.0.0 │
╰─────────────────────────────────────────────╯
``` 
This new version uses `agentOptions: { rejectUnauthorized: false }` instead of `strictSSL`

**Pull request merged**
